profile: cover.out
local-prefix: github.com/mikerudolph/artifacts
threshold:
  file: 70
  package: 85
  total: 85
exclude:
  paths:
    - migrations/.*
    - cmd/artifacts/main.go
    - examples/.*
    - internal/store/object/objecttest/.*
