DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS api_tokens;
DROP TABLE IF EXISTS repo_tokens;
DROP TABLE IF EXISTS refs;
DROP TABLE IF EXISTS repos;
DROP TABLE IF EXISTS namespaces;
DROP TABLE IF EXISTS accounts;
